# Generated by Django 4.0.1 on 2022-10-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ortak',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=4, primary_key=True, serialize=False)),
                ('Marka', models.CharField(db_column='Marka', max_length=30)),
                ('Model', models.CharField(db_column='Model', max_length=100)),
                ('Isletim_Sistemi', models.CharField(db_column='Isletim Sistemi', max_length=100)),
                ('Islemci', models.CharField(db_column='Islemci', max_length=100)),
                ('Bellek', models.CharField(db_column='Bellek', max_length=30)),
                ('Disk', models.CharField(db_column='Disk', max_length=50)),
                ('Ekran_Boyutu', models.CharField(db_column='Ekran Boyutu', max_length=20)),
                ('Baslik', models.CharField(db_column='Baslik', max_length=255)),
                ('Resim', models.CharField(db_column='Foto', max_length=255)),
                ('Puan', models.CharField(db_column='Puan', max_length=3)),
                ('Fiyat', models.CharField(db_column='Fiyat', max_length=7)),
                ('N11', models.CharField(db_column='N11', max_length=50)),
                ('Hepsi', models.CharField(db_column='Hepsi', max_length=50)),
                ('Trend', models.CharField(db_column='Trend', max_length=50)),
            ],
            options={
                'db_table': 'ortak',
                'managed': False,
            },
        ),
    ]
